oxycalib <- vector(mode = 'list')
# note : using the CTD calibration date to hook up the appropriate coefficients to use
#        sometimes the calibration of the oxygen sensor was done before/after to CTD
#        so the month here might differ by one from what is actually on the calibration sheets.
#        notes have been made for these instances.
oxycalib[[1]] <- list(serialNumber = '43-3338',
                      model = 'SBE43F',
                      calibrationDate = '20160421', # note : oxy cal sheet says Apr but CTD calib in May
                      calibrationCoefficients = data.frame(Soc = 3.2305e-4,
                                                           Foffset = -830.74,
                                                           Tau20 = 1.40,
                                                           A = -3.4562e-3,
                                                           B = 1.1709e-4,
                                                           C = -1.7302e-6,
                                                           Enom = 0.036))

oxycalib[[2]] <- list(serialNumber = '43-3338',
                      model = 'SBE43F',
                      calibrationDate = '20181219',
                      calibrationCoefficients = data.frame(Soc = 2.8895e-4,
                                                           Foffset = -835.35,
                                                           Tau20 = 1.16,
                                                           A = -3.76649e-3,
                                                           B = 1.1716e-4,
                                                           C = -1.3298e-6,
                                                           Enom = 0.036))
oxycalib[[3]] <- list(serialNumber = '43-3338',
                      model = 'SBE43F',
                      calibrationDate = '20190725', # note : oxy cal sheet says Jul but CTD calib in Aug
                      calibrationCoefficients = data.frame(Soc = 2.9006e-4,
                                                           Foffset = -829.48,
                                                           Tau20 = 1.06,
                                                           A = -4.4375e-3,
                                                           B = 1.7964e-4,
                                                           C = -2.8796e-6,
                                                           Enom = 0.036))
oxycalib[[4]] <- list(serialNumber = '43-3338',
                      model = 'SBE43F',
                      calibrationDate = '20210206',
                      calibrationCoefficients = data.frame(Soc = 2.7703e-4,
                                                           Foffset = -844.41,
                                                           Tau20 = 0.98,
                                                           A = -5.0876e-3,
                                                           B = 2.4486e-4,
                                                           C = -3.5643e-6,
                                                           Enom = 0.036))
oxycalib[[5]] <- list(serialNumber = '43-3336',
                      model = 'SBE43F',
                      calibrationDate = '20160422', # note : oxy cal sheet says Apr but CTD calib in May
                      calibrationCoefficients = data.frame(Soc = 2.7945e-4,
                                                           Foffset = -794.20,
                                                           Tau20 = 1.91,
                                                           A = -3.4437e-3,
                                                           B = 1.5480e-4,
                                                           C = -2.3721e-6,
                                                           Enom = 0.036))
oxycalib[[6]] <- list(serialNumber = '43-3336',
                      model = 'SBE43F',
                      calibrationDate = '20180818',
                      calibrationCoefficients = data.frame(Soc = 2.8722e-4,
                                                           Foffset = -777.23,
                                                           Tau20 = 1.09,
                                                           A = -4.4454e-3,
                                                           B = 1.8630e-4,
                                                           C = -2.8650e-6,
                                                           Enom = 0.036))
oxycalib[[7]] <- list(serialNumber = '43-3336',
                      model = 'SBE43F',
                      calibrationDate = '20220201',
                      calibrationCoefficients = data.frame(Soc = 3.0667e-4,
                                                           Foffset = -878.86,
                                                           Tau20 = 1.26,
                                                           A = -4.6593e-3,
                                                           B = 1.7954e-4,
                                                           C = -2.2483e-6,
                                                           Enom = 0.036))
oxycalib[[8]] <- list(serialNumber = '43-3336',
                      model = 'SBE43',
                      calibrationDate = '20191220',
                      calibrationCoefficients = data.frame(Soc = 3.0636e-4,
                                                           Foffset = -785.65,
                                                           Tau20 = 1.02,
                                                           A = -4.3009e-3,
                                                           B = 1.5565e-4,
                                                           C = -1.9609e-6,
                                                           Enom = 0.036))
oxycalib[[9]] <- list(serialNumber = '43-3276',
                      model = 'SBE43',
                      calibrationDate = '20160130', # note : oxy cal sheet says Jan but CTD calib in Mar
                      calibrationCoefficients = data.frame(Soc = 3.1884e-4,
                                                           Foffset = -807.15,
                                                           Tau20 = 1.67,
                                                           A = -4.2074e-3,
                                                           B = 2.2413e-4,
                                                           C = -3.4516e-6,
                                                           Enom = 0.036))
oxycalib[[10]] <- list(serialNumber = '43-3276',
                      model = 'SBE43',
                      calibrationDate = '20190312', # note : oxy cal sheet says Mar but CTD calib in Apr
                      calibrationCoefficients = data.frame(Soc = 2.9165e-4,
                                                           Foffset = -800.49,
                                                           Tau20 = 1.11,
                                                           A = -5.0595e-3,
                                                           B = 2.3090e-4,
                                                           C = -3.2232e-6,
                                                           Enom = 0.036))
oxycalib[[11]] <- list(serialNumber = '43-3276',
                       model = 'SBE43',
                       calibrationDate = '20211222', # '20211222' # note : oxy cal sheet says Dec but CTD calib in Feb
                       calibrationCoefficients = data.frame(Soc = 3.4723e-4,
                                                            Foffset = -836.94,
                                                            Tau20 = 1.86,
                                                            A = -4.9987e-3,
                                                            B = 1.1906e-4,
                                                            C = -8.0425e-7,
                                                            Enom = 0.036))
oxycalib[[12]] <- list(serialNumber = '43-3276',
                       model = 'SBE43',
                       calibrationDate = '20230929', # '20211222' # note : oxy cal sheet says Dec but CTD calib in Feb
                       calibrationCoefficients = data.frame(Soc = 3.3539e-4,
                                                            Foffset = -810.81,
                                                            Tau20 = 1.86,
                                                            A = -4.8893e-3,
                                                            B = 2.237e-4,
                                                            C = -3.3703e-6,
                                                            Enom = 0.036))

oxycalib[[13]] <- list(serialNumber = '43-3365',
                      model = 'SBE43F',
                      calibrationDate = '20160420', # note : oxy cal sheet says Apr but CTD calib in May
                      calibrationCoefficients = data.frame(Soc = 2.8277e-4,
                                                           Foffset = -847.84,
                                                           Tau20 = 1.40,
                                                           A = -2.8377e-3,
                                                           B = 1.2076e-4,
                                                           C = -2.0639e-6,
                                                           Enom = 0.036))
oxycalib[[14]] <- list(serialNumber = '43-3365',
                      model = 'SBE43F',
                      calibrationDate = '20180814', # note : oxy cal sheet says Aug but CTD calib in Jul
                      calibrationCoefficients = data.frame(Soc = 3.1993e-4,
                                                           Foffset = -834.99,
                                                           Tau20 = 0.98,
                                                           A = -3.6818e-3,
                                                           B = 1.4127e-4,
                                                           C = -2.2880e-6,
                                                           Enom = 0.036))
oxycalib[[15]] <- list(serialNumber = '43-3365',
                       model = 'SBE43F',
                       calibrationDate = '20190818',
                       calibrationCoefficients = data.frame(Soc = 3.3836e-4,
                                                            Foffset = -835.39,
                                                            Tau20 = 1.18,
                                                            A = -3.4671e-3,
                                                            B = 1.2564e-4,
                                                            C = -1.7894e-6,
                                                            Enom = 0.036))
oxycalib[[16]] <- list(serialNumber = '43-3365',
                       model = 'SBE43F',
                       calibrationDate = '20210105',
                       calibrationCoefficients = data.frame(Soc = 3.3498e-4,
                                                            Foffset = -851.20,
                                                            Tau20 = 1.61,
                                                            A = -4.2429e-3,
                                                            B = 1.9045e-4,
                                                            C = -3.1421e-6,
                                                            Enom = 0.036))
oxycalib[[17]] <- list(serialNumber = '43-3365',
                       model = 'SBE43F',
                       calibrationDate = '20230121',
                       calibrationCoefficients = data.frame(Soc = 3.2649e-4,
                                                            Foffset = -839.79,
                                                            Tau20 = 1.23,
                                                            A = -3.7164e-3,
                                                            B = 1.6743e-4,
                                                            C = -2.7266e-6,
                                                            Enom = 0.036))
oxycalib[[18]] <- list(serialNumber = '43-3365',
                       model = 'SBE43F',
                       calibrationDate = '20240131',
                       calibrationCoefficients = data.frame(Soc = 2.6773e-4,
                                                            Foffset = -800.03,
                                                            Tau20 = 1.27,
                                                            A = -3.3140-3,
                                                            B = 1.0937-4,
                                                            C = -1.9124-6,
                                                            Enom = 0.036))